spring:
  profiles:
    include: core-hsqldb
  jpa:
    properties:
      hibernate:
          hbm2ddl.auto: validate
          show_sql: false
          format_sql: false
          use_sql_comments: false
liquibase:
  change-log: classpath:/db/changelog/master.xml